# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  name: default  # name of the pool to run this job in

resources:
  repositories:
  - repository: software
    type: github
    name: Keristero/CItestingSoftware
    trigger:
    - master
    endpoint: Keristero/CItestingSoftware #only needed for non azure repositories
  - repository: testHarness
    type: github
    name: Keristero/CItesting
    trigger:
    - master
    endpoint: Keristero/CItesting #only needed for non azure repositories

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'npm install and test'

# Publish Test Results
# Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '**/test-results*.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional
